// src/utils/data.ts

// Complete list of feelings (categories and subcategories)
export const feelings = {
    Happy: [
      'Playful',
      'Content',
      'Interested',
      'Proud',
      'Accepted',
      'Powerful',
      'Peaceful',
      'Trusting',
      'Optimistic',
      'Joyful',
      'Free',
      'Cheeky',
      'Energetic',
      'Aroused',
      'Alive',
      'Excited',
      'Amazed',
      'Awed',
      'Eager',
    ],
    Sad: [
      'Lonely',
      'Vulnerable',
      'Despair',
      'Guilty',
      'Depressed',
      'Hurt',
      'Abandoned',
      'Victimized',
      'Fragile',
      'Grief',
      'Powerless',
      'Ashamed',
      'Empty',
      'Inferior',
      'Embarrassed',
      'Disappointed',
      'Horrified',
      'Devastated',
    ],
    Angry: [
      'Let Down',
      'Humiliated',
      'Bitter',
      'Mad',
      'Aggressive',
      'Frustrated',
      'Distant',
      'Critical',
      'Betrayed',
      'Resentful',
      'Disrespected',
      'Ridiculed',
      'Indignant',
      'Violent',
      'Furious',
      'Jealous',
      'Provoked',
      'Hostile',
      'Infuriated',
      'Annoyed',
      'Withdrawn',
      'Numb',
    ],
    Fearful: [
      'Scared',
      'Anxious',
      'Insecure',
      'Weak',
      'Rejected',
      'Threatened',
      'Helpless',
      'Frightened',
      'Overwhelmed',
      'Worried',
      'Inadequate',
      'Insignificant',
      'Excluded',
      'Persecuted',
      'Nervous',
      'Exposed',
    ],
    Surprised: [
      'Startled',
      'Confused',
      'Amazed',
      'Excited',
      'Stunned',
      'Disillusioned',
      'Perplexed',
      'Astonished',
    ],
    Bad: [
      'Bored',
      'Busy',
      'Stressed',
      'Tired',
      'Apathetic',
      'Indifferent',
      'Rushed',
      'Pressured',
      'Helpless',
      'Overwhelmed',
      'Worried',
      'Inadequate',
    ],
  };
  
  export const categoryColors = {
    Happy: 'bg-yellow-200',
    Sad: 'bg-blue-200',
    Angry: 'bg-red-200',
    Fearful: 'bg-green-200',
    Surprised: 'bg-purple-200',
    Bad: 'bg-orange-200',
  };
  
  export const negativeCognitions = [
    "I don’t deserve love.",
    "I am a bad person.",
    "I am terrible.",
    "I am worthless.",
    "I am shameful.",
    "I am not lovable.",
    "I am not good enough.",
    "I deserve only bad things.",
    "I am permanently damaged.",
    "I am ugly.",
    "I do not deserve good things.",
    "I am stupid.",
    "I am insignificant.",
    "I am a disappointment.",
    "I deserve to die.",
    "I deserve to be miserable.",
    "I am different.",
    "I should have done something.",
    "I did something wrong.",
    "I should have known better.",
    "I cannot be trusted.",
    "I cannot trust myself.",
    "I cannot trust my judgment.",
    "I cannot trust anyone.",
    "I cannot protect myself.",
    "I am in danger.",
    "It’s not okay to feel.",
    "I cannot stand up for myself.",
    "I cannot let it out.",
    "I am not in control.",
    "I am powerless.",
    "I am weak.",
    "I cannot get what I want.",
    "I am a failure.",
    "I cannot succeed.",
    "I have to be perfect.",
    "I cannot stand it.",
    "I am inadequate.",
  ];
  
  export const positiveCognitions = [
    "I deserve love.",
    "I am a good person.",
    "I am fine as I am.",
    "I am worthy.",
    "I am honorable.",
    "I am lovable.",
    "I deserve good things.",
    "I am healthy.",
    "I am fine.",
    "I can have good things.",
    "I am intelligent.",
    "I am significant.",
    "I am okay just the way I am.",
    "I deserve to live.",
    "I deserve to be happy.",
    "I am okay as I am.",
    "I did the best I could.",
    "I can learn from it.",
    "I do the best I can.",
    "I can be trusted.",
    "I can trust myself.",
    "I can trust my judgment.",
    "I can choose whom to trust.",
    "I can take care of myself.",
    "It’s over; I am safe now.",
    "I can safely feel my emotions.",
    "I can make my needs known.",
    "I can let it out.",
    "I am in control.",
    "I have choices.",
    "I am strong.",
    "I can get what I want.",
    "I can succeed.",
    "I can be myself.",
    "I can handle it.",
    "I am capable.",
  ];
  