name: Deploy to GitHub Pages

on:
  push:
    branches:
      - static-page

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run clean && NEXT_PUBLIC_ENV=production npm run build

      - name: Deploy to GitHub Pages
        run: |
          touch out/.nojekyll
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add out
          git commit -m '[deploy] Deploy to GitHub Pages'
          git push origin `git subtree split --prefix out main`:gh-pages --force